#!/bin/bash

# Check newest version
# * https://pypi.python.org/pypi/numpy
# * https://pypi.python.org/pypi/scipy
# * https://pypi.python.org/pypi/pandas
# * https://pypi.python.org/pypi/matplotlib
# * https://pypi.python.org/pypi/scikit-learn
# * https://github.com/numpy/numpy/tags
# * https://github.com/scipy/scipy/tags
# * https://github.com/pydata/pandas/tags
# * https://github.com/matplotlib/matplotlib/tags
# * https://github.com/scikit-learn/scikit-learn/tags

DST=`pwd`"/build/.local"

if ! [ -e $DST/bin/pyvenv ]; then
  pushd `pwd`
  echo ">>>>> Building Python"
  mkdir -p $DST
  mkdir -p build
  cd build
  wget https://www.python.org/ftp/python/3.4.1/Python-3.4.1.tgz
  tar zxvf Python-3.4.1.tgz
  cd Python-3.4.1
  ./configure --prefix $DST && make && make install
  popd
fi

$DST/bin/pyvenv venv
source venv/bin/activate
[ $? -eq 0 ] && pip install -r requirements.txt
[ $? -eq 0 ] && pip install https://github.com/smly/python-jsonnet/archive/v0.0.1.zip
