#!/bin/bash

# Check newest version
# * https://pypi.python.org/pypi/numpy
# * https://pypi.python.org/pypi/scipy
# * https://pypi.python.org/pypi/pandas
# * https://pypi.python.org/pypi/matplotlib
# * https://pypi.python.org/pypi/scikit-learn
# * https://github.com/numpy/numpy/tags
# * https://github.com/scipy/scipy/tags
# * https://github.com/pydata/pandas/tags
# * https://github.com/matplotlib/matplotlib/tags
# * https://github.com/scikit-learn/scikit-learn/tags

NUMPY="1.8.2"
SCIPY="0.14.0"
PANDAS="0.14.1"
MATPLOTLIB="1.3.1"
SKLEARN="0.15.1"

DST=`pwd`"/build/.local"

if ! [ -e $DST/bin/pyvenv ]; then
  pushd `pwd`
  echo ">>>>> Building Python"
  mkdir -p $DST
  mkdir -p build
  cd build
  wget https://www.python.org/ftp/python/3.4.1/Python-3.4.1.tgz
  tar zxvf Python-3.4.1.tgz
  cd Python-3.4.1
  ./configure --prefix $DST && make && make install
  popd
fi

$DST/bin/pyvenv venv
source venv/bin/activate
[ $? -eq 0 ] && pip install numpy==${NUMPY}
[ $? -eq 0 ] && pip install scipy==${SCIPY}
[ $? -eq 0 ] && pip install pandas==${PANDAS}
[ $? -eq 0 ] && pip install matplotlib==${MATPLOTLIB}
[ $? -eq 0 ] && pip install scikit-learn==${SKLEARN}
