#!/bin/zsh

function cd() { builtin cd $@ && ls --color }
function pcat() { cat /proc/$1/status }
function histall { history -E 1 }

function vol() {
    local volume=$1
    amixer set Master $1% unmute
}

function call() {
    local message=$1
    curl -d "message=$message" http://im.kayac.com/api/post/smly
}

function loopn() {
    while (true); do echo $@ ; $1 $@ -novideo 1>& /dev/null; sleep 3; done
}

# Extract archives
function extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1        ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1       ;;
            *.rar)       rar x $1     ;;
            *.gz)        gunzip $1     ;;
            *.tar)       tar xf $1        ;;
            *.tbz2)      tar xjf $1      ;;
            *.tgz)       tar xzf $1       ;;
            *.zip)       unzip $1     ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1    ;;
            *)           echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# function flv2mp3() {
#     if [ -f $1 ] ; then
#       ffmpeg -y -i $1 -acodec copy $2
#     else
#         echo "'$1' is not a valid file"
#     fi
# }
