;; -*- Mode: Emacs-Lisp ; Coding: utf-8 -*-

(set-background-color "black")
(set-foreground-color "white")
(set-cursor-color "yellow")
(set-face-foreground 'font-lock-comment-face "Brown")
(set-face-foreground 'font-lock-string-face  "coral")
(set-face-foreground 'font-lock-keyword-face "violet")
(set-face-foreground 'font-lock-function-name-face "white")
(set-face-foreground 'font-lock-variable-name-face "white")
(set-face-foreground 'font-lock-type-face "skyblue1")
(set-face-foreground 'font-lock-warning-face "yellow")
(set-face-foreground 'font-lock-builtin-face "tomato")
(set-face-foreground 'font-lock-constant-face "goldenrod")
(set-face-background 'highlight "yellow")
(set-face-foreground 'highlight "black")
(set-face-background 'region "NavyBlue")
(set-face-foreground 'region "SteelBlue4")

;; color-settings
(set-face-foreground 'modeline "white")
(set-face-background 'modeline "Red4")
(set-face-foreground 'mode-line-inactive "Firebrick")
(set-face-background 'mode-line-inactive "black")
(set-face-foreground 'minibuffer-prompt "Red")
